CREATE TABLE entrenadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    especialidad VARCHAR(255) NOT NULL,
    anios_experiencia INTEGER NOT NULL,
    telefono VARCHAR(255),
    correo VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL,
    CONSTRAINT uk_entrenadores_correo UNIQUE (correo)
);
