spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: member-service
              uri: lb://member-service
              predicates: [Path=/member-app/**]
              filters: [StripPrefix=1]
            - id: membership-service
              uri: lb://membership-service
              predicates: [Path=/membership-app/**]
              filters: [StripPrefix=1]
            - id: payment-service
              uri: lb://payment-service
              predicates: [Path=/payment-app/**]
              filters: [StripPrefix=1]
            - id: class-service
              uri: lb://class-service
              predicates: [Path=/class-app/**]
              filters: [StripPrefix=1]
            - id: booking-service
              uri: lb://booking-service
              predicates: [Path=/booking-app/**]
              filters: [StripPrefix=1]
            - id: trainer-service
              uri: lb://trainer-service
              predicates: [Path=/trainer-app/**]
              filters: [StripPrefix=1]
            - id: access-service
              uri: lb://access-service
              predicates: [Path=/access-app/**]
              filters: [StripPrefix=1]
            - id: equipment-service
              uri: lb://equipment-service
              predicates: [Path=/equipment-app/**]
              filters: [StripPrefix=1]
            - id: branch-service
              uri: lb://branch-service
              predicates: [Path=/branch-app/**]
              filters: [StripPrefix=1]
            - id: notification-service
              uri: lb://notification-service
              predicates: [Path=/notification-app/**]
              filters: [StripPrefix=1]
          default-filters:
            - AddResponseHeader=X-IronFlow-Gateway, api-gateway
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: ['*']
                allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
                allowed-headers: ['*']

server:
  port: ${PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
