CREATE TABLE planes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    precio DOUBLE PRECISION NOT NULL,
    dias_duracion INTEGER NOT NULL,
    estado VARCHAR(255) NOT NULL
);

CREATE TABLE planes_miembros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    miembro_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP NOT NULL,
    CONSTRAINT fk_planes_miembros_plan FOREIGN KEY (plan_id) REFERENCES planes (id)
);
