CREATE TABLE tipos_clase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255),
    estado VARCHAR(255) NOT NULL,
    CONSTRAINT uk_tipos_clase_nombre UNIQUE (nombre)
);

CREATE TABLE horarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_clase_id BIGINT NOT NULL,
    entrenador_id BIGINT NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    aforo_max INTEGER NOT NULL,
    aforo_actual INTEGER NOT NULL,
    estado VARCHAR(255) NOT NULL,
    CONSTRAINT fk_horarios_tipo_clase FOREIGN KEY (tipo_clase_id) REFERENCES tipos_clase (id)
);
