CREATE TABLE sucursales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    ciudad VARCHAR(255),
    direccion VARCHAR(255),
    telefono VARCHAR(255),
    horario_atencion VARCHAR(255),
    estado VARCHAR(255),
    activa BOOLEAN
);
