spring:
  application:
    name: class-service
  profiles:
    default: h2
  jpa:
    open-in-view: false

services:
  trainer:
    base-url: ${TRAINER_SERVICE_URL:http://localhost:8086/trainer-app}

server:
  port: 8084
  servlet:
    context-path: /class-app
