CREATE TABLE equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    ubicacion VARCHAR(255) NOT NULL,
    cantidad_disponible INTEGER NOT NULL,
    mantenimiento_requerido BOOLEAN NOT NULL
);
