spring.application.name=member-service
spring.profiles.default=h2
server.port=8081
server.servlet.context-path=/member-app
spring.jpa.open-in-view=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
