CREATE TABLE miembros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    rut VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefono VARCHAR(255),
    estado VARCHAR(255) NOT NULL,
    CONSTRAINT uk_miembros_rut UNIQUE (rut),
    CONSTRAINT uk_miembros_email UNIQUE (email)
);
